const types = {
  FETCH_DRIVERS_REQUEST: 'LIST_DRIVERS_REQUEST',
  FETCH_DRIVERS_SUCCESS: 'LIST_DRIVERS_SUCCESS',
  FETCH_DRIVERS_ERROR: 'LIST_DRIVERS_ERROR',

  FETCH_TRAVELS_REQUEST: 'LIST_TRAVELS_REQUEST',
  FETCH_TRAVELS_SUCCESS: 'LIST_TRAVELS_SUCCESS',
  FETCH_TRAVELS_ERROR: 'LIST_TRAVELS_ERROR',
};

export default types;
